services:
  # PostgreSQL database container
  db:
    image: postgres:17
    container_name: forge_db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "7654:5432" # Expose PostgreSQL port for local access
    restart: unless-stopped

  # Django rest API container
  api:
    container_name: api
    build: .
    command: >
      sh -c "
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      gunicorn -k uvicorn.workers.UvicornWorker prompt_forge.asgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - .:/app
    environment:
      - DEBUG=False
      - DATABASE_HOST=db
    ports:
      - "8000:8000" # Expose Django app on port 8000
    depends_on:
      - db
    restart: unless-stopped

  # PgAdmin container for managing PostgreSQL visually
  pgadmin:
    image: dpage/pgadmin4
    container_name: forge_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80" # Access PgAdmin at http://localhost:5050
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    restart: unless-stopped
    depends_on:
      - api

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}?sslmode=disable"
    ports:
      - "9187:9187"
    restart: unless-stopped
    depends_on:
      - db

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "8585:3000"
    restart: unless-stopped
    depends_on:
      - prometheus

# Named volumes for persistent data
volumes:
  postgres_data:
  pgadmin_data:
