global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'django'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8000']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
