# Generated by Django 5.2.7 on 2025-10-18 03:06

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PromptEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='text-embedding-3-small', max_length=100)),
                ('vector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='forge.prompt')),
            ],
        ),
        migrations.CreateModel(
            name='PromptMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_used', models.CharField(default='gpt-3.5-turbo', max_length=50)),
                ('sent_via_websocket', models.BooleanField(default=False)),
                ('extra_info', models.JSONField(blank=True, null=True)),
                ('prompt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='forge.prompt')),
            ],
        ),
    ]
