name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint PromptForge App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install linting dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  test:
    name: Test PromptForge App
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          python manage.py migrate
        env:
          CI: true
          SECRET_KEY: test-secret-key-for-ci
          DEBUG: True
          # Postgres env to avoid CI errors
          DATABASE_NAME: "test_db"
          DATABASE_USER: "postgres"
          DATABASE_PASSWORD: "postgres"
          DATABASE_HOST: "localhost"
          DATABASE_PORT: 5432

      - name: Run tests with SQLite
        run: |
          pytest --ds=prompt_forge.settings -v
        env:
          CI: true
          SECRET_KEY: test-secret-key-for-ci
          DEBUG: True
          # Postgres env to avoid CI errors
          DATABASE_NAME: "test_db"
          DATABASE_USER: "postgres"
          DATABASE_PASSWORD: "postgres"
          DATABASE_HOST: "localhost"
          DATABASE_PORT: 5432

  deploy:
    name: Deploy with Terraform
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        # with:
        #   terraform_version: 1.13.4

      - name: Terraform Init & Apply
        if: false
        run: |
          cd terraform
          # Initialize Terraform providers and modules
          terraform init
          # Apply deployment to the server
          terraform apply -auto-approve \
            -var "deploy_host=${{ secrets.DEPLOY_HOST }}" \
            -var "deploy_user=${{ secrets.DEPLOY_USER }}" \
            -var "ssh_private_key=${{ secrets.DEPLOY_SSH_KEY }}" \
            -var "env_vars=${{ secrets.ENV_VARS }}"
