name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          python manage.py migrate
        env:
          CI: true
          SECRET_KEY: test-secret-key-for-ci
          DEBUG: True
          # Postgres env to avoid CI errors
          DATABASE_NAME: "test_db"
          DATABASE_USER: "postgres"
          DATABASE_PASSWORD: "postgres"
          DATABASE_HOST: "localhost"
          DATABASE_PORT: 5432

      - name: Run tests with SQLite
        run: |
          pytest --ds=prompt_forge.settings -v
        env:
          CI: true
          SECRET_KEY: test-secret-key-for-ci
          DEBUG: True
          # Postgres env to avoid CI errors
          DATABASE_NAME: "test_db"
          DATABASE_USER: "postgres"
          DATABASE_PASSWORD: "postgres"
          DATABASE_HOST: "localhost"
          DATABASE_PORT: 5432
